apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: role:spark
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - pods
      - pods/log
      - services
      - persistentvolumeclaims
    verbs:
      - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: role:spark
subjects:
  - kind: ServiceAccount
    name: spark-sa
